For this notebook we need IMDB dataset from Kaggle
https://www.kaggle.com/stefanoleone992/imdb-extensive-dataset

In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import os

pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

PATH_PREFIX = '../'
DATA_DIR = "data"

In [2]:
mv = pd.read_parquet(os.path.join(PATH_PREFIX, DATA_DIR, 'movies.parquet'))
mv.head()

,title,description,pa,te_zien_tot,genre,land,taal,ondertitels,speelduur,regisseur,distributeur,min_age,duration_min,director_norm,title_norm,primary_genre
0,El perro que no calla,Sebastián is een dertiger met een hond en een ...,Alle leeftijden,20 december 2021,drama,Argentinië,Spaans,Nederlands,73 min.,Ana Katz,Periscoop Film,0,73,ana katz,el perro que no calla,drama
1,Hoogtijdagen,Op het schiereiland Kola zijn de sporen van de...,Alle leeftijden,20 december 2021,documentaire,Nederland,Russisch,Nederlands,90 min.,Ben van Lieshout,Cinema Delicatessen,0,90,ben van lieshout,hoogtijdagen,documentaire
2,Oliver Sacks: His Own Life,Een paar weken na het afronden van zijn memoir...,Alle leeftijden,13 december 2021,documentaire,Verenigde Staten,Engels,Nederlands,94 min.,Ric Burns,Periscoop Film,0,94,ric burns,oliver sacks: his own life,documentaire
3,Lapsis,De komst van een nieuwe vorm van bankieren zet...,Mogelijk schadelijk tot 16 jaar,13 december 2021,"drama, mysterie, sciencefiction",Verenigde Staten,Engels,Nederlands,108 min.,Noah Hutton,De Filmfreak,16,108,noah hutton,lapsis,drama
4,Sweat,Wanneer fitnesscoach en influencer Sylwia Zaja...,Mogelijk schadelijk tot 16 jaar,13 december 2021,drama,Polen,Pools,Nederlands,105 min.,Magnus von Horn,Imagine Filmdistributie Nederland,16,105,magnus von horn,sweat,drama

In [3]:
imdb_mv = pd.read_csv(os.path.join(PATH_PREFIX, DATA_DIR, "imdb_archive/IMDb movies.csv"), index_col='imdb_title_id')
imdb_mv.head()

/anaconda3/envs/py37/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
imdb_title_id,,,,,,,,,,,,,,,,,,,,,
tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [4]:
imdb_rat = pd.read_csv(os.path.join(PATH_PREFIX, DATA_DIR, "imdb_archive/IMDb ratings.csv"), index_col='imdb_title_id')
imdb_rat.head()

,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,votes_5,votes_4,votes_3,votes_2,votes_1,allgenders_0age_avg_vote,allgenders_0age_votes,allgenders_18age_avg_vote,allgenders_18age_votes,allgenders_30age_avg_vote,allgenders_30age_votes,allgenders_45age_avg_vote,allgenders_45age_votes,males_allages_avg_vote,males_allages_votes,males_0age_avg_vote,males_0age_votes,males_18age_avg_vote,males_18age_votes,males_30age_avg_vote,males_30age_votes,males_45age_avg_vote,males_45age_votes,females_allages_avg_vote,females_allages_votes,females_0age_avg_vote,females_0age_votes,females_18age_avg_vote,females_18age_votes,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes
imdb_title_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,28,9,1,5,14,7.2,4.0,6.0,38.0,5.7,50.0,6.6,35.0,6.2,97.0,7.0,1.0,5.9,24.0,5.6,36.0,6.7,31.0,6.0,35.0,7.3,3.0,5.9,14.0,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0
tt0000574,6.1,589,6.3,6.0,57,18,58,137,139,103,28,20,13,16,6.0,1.0,6.1,114.0,6.0,239.0,6.3,115.0,6.1,425.0,6.0,1.0,6.2,102.0,6.0,210.0,6.2,100.0,6.2,50.0,NaN,NaN,5.9,12.0,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0
tt0001892,5.8,188,6.0,6.0,6,6,17,44,52,32,16,5,6,4,NaN,NaN,5.5,25.0,5.8,72.0,6.2,62.0,5.9,146.0,NaN,NaN,5.5,21.0,5.9,67.0,6.2,55.0,5.7,15.0,NaN,NaN,5.8,4.0,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0
tt0002101,5.2,446,5.3,5.0,15,8,16,62,98,117,63,26,25,16,NaN,NaN,5.3,23.0,5.0,111.0,5.3,193.0,5.1,299.0,NaN,NaN,5.2,20.0,4.9,96.0,5.2,171.0,5.9,39.0,NaN,NaN,5.7,3.0,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0
tt0002130,7.0,2237,6.9,7.0,210,225,436,641,344,169,66,39,20,87,7.5,4.0,7.0,402.0,7.0,895.0,7.1,482.0,7.0,1607.0,8.0,2.0,7.0,346.0,7.0,804.0,7.0,396.0,7.2,215.0,7.0,2.0,7.0,52.0,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0

In [5]:
imdb_rat_mv = imdb_rat.join(imdb_mv, how='inner')
imdb_rat_mv.head()

,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,votes_5,votes_4,votes_3,votes_2,votes_1,allgenders_0age_avg_vote,allgenders_0age_votes,allgenders_18age_avg_vote,allgenders_18age_votes,allgenders_30age_avg_vote,allgenders_30age_votes,allgenders_45age_avg_vote,allgenders_45age_votes,males_allages_avg_vote,males_allages_votes,males_0age_avg_vote,males_0age_votes,males_18age_avg_vote,males_18age_votes,males_30age_avg_vote,males_30age_votes,males_45age_avg_vote,males_45age_votes,females_allages_avg_vote,females_allages_votes,females_0age_avg_vote,females_0age_votes,females_18age_avg_vote,females_18age_votes,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics
imdb_title_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
tt0000009,5.9,154,5.9,6.0,12,4,10,43,28,28,9,1,5,14,7.2,4.0,6.0,38.0,5.7,50.0,6.6,35.0,6.2,97.0,7.0,1.0,5.9,24.0,5.6,36.0,6.7,31.0,6.0,35.0,7.3,3.0,5.9,14.0,5.7,13.0,4.5,4.0,5.7,34.0,6.4,51.0,6.0,70.0,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,5.9,154,NaN,NaN,NaN,NaN,1.0,2.0
tt0000574,6.1,589,6.3,6.0,57,18,58,137,139,103,28,20,13,16,6.0,1.0,6.1,114.0,6.0,239.0,6.3,115.0,6.1,425.0,6.0,1.0,6.2,102.0,6.0,210.0,6.2,100.0,6.2,50.0,NaN,NaN,5.9,12.0,6.2,23.0,6.6,14.0,6.4,66.0,6.0,96.0,6.2,331.0,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,6.1,589,$ 2250,NaN,NaN,NaN,7.0,7.0
tt0001892,5.8,188,6.0,6.0,6,6,17,44,52,32,16,5,6,4,NaN,NaN,5.5,25.0,5.8,72.0,6.2,62.0,5.9,146.0,NaN,NaN,5.5,21.0,5.9,67.0,6.2,55.0,5.7,15.0,NaN,NaN,5.8,4.0,5.8,4.0,6.8,7.0,5.4,32.0,6.2,31.0,5.9,123.0,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,5.8,188,NaN,NaN,NaN,NaN,5.0,2.0
tt0002101,5.2,446,5.3,5.0,15,8,16,62,98,117,63,26,25,16,NaN,NaN,5.3,23.0,5.0,111.0,5.3,193.0,5.1,299.0,NaN,NaN,5.2,20.0,4.9,96.0,5.2,171.0,5.9,39.0,NaN,NaN,5.7,3.0,5.5,14.0,6.1,21.0,4.9,57.0,5.5,207.0,4.7,105.0,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,5.2,446,$ 45000,NaN,NaN,NaN,25.0,3.0
tt0002130,7.0,2237,6.9,7.0,210,225,436,641,344,169,66,39,20,87,7.5,4.0,7.0,402.0,7.0,895.0,7.1,482.0,7.0,1607.0,8.0,2.0,7.0,346.0,7.0,804.0,7.0,396.0,7.2,215.0,7.0,2.0,7.0,52.0,7.3,82.0,7.4,77.0,6.9,139.0,7.0,488.0,7.0,1166.0,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,7.0,2237,NaN,NaN,NaN,NaN,31.0,14.0

In [6]:
imdb_rat_mv[['title','weighted_average_vote']]

                                        title  weighted_average_vote
imdb_title_id
tt0000009                          Miss Jerry                    5.9
tt0000574         The Story of the Kelly Gang                    6.1
tt0001892                      Den sorte drøm                    5.8
tt0002101                           Cleopatra                    5.2
tt0002130                           L'Inferno                    7.0
...                                       ...                    ...
tt9908390                             Le lion                    5.3
tt9911196      De Beentjes van Sint-Hildegard                    7.7
tt9911774           Padmavyuhathile Abhimanyu                    7.9
tt9914286                   Sokagin Çocuklari                    6.4
tt9914942          La vida sense la Sara Amat                    6.7

[85855 rows x 2 columns]

In [7]:
# search by name is difficult because of different spelling
name='Cameron Post'
#name = 'Indifferenti'
imdb_rat_mv[imdb_rat_mv.title.str.contains(name)].title

imdb_title_id
tt6257174    La diseducazione di Cameron Post
Name: title, dtype: object

In [8]:
mv.regisseur.value_counts()

Wong Kar Wai                                6
Michael Winterbottom                        3
Luca Guadagnino                             2
Magnus von Horn                             1
Tove Undheim                                1
Benoît Delépine, Gustave Kervern            1
Oskar Roehler                               1
Zaida Bergroth                              1
Abdellatif Kechiche                         1
James Ivory                                 1
David Färdmar                               1
Gabriela Cowperthwaite                      1
Harry Wootliff                              1
Benjamin Ree                                1
Mahnaz Mohammadi                            1
Eefje Blankevoort, Els van Driel            1
Todd Haynes                                 1
Cindy Kerseborn                             1
Kirill Mikhanovsky                          1
Pema Tseden                                 1
Lemohang Jeremiah Mosese                    1
Anna Kerrigan                               1
Radu Jude                                   1
Larisa Sadilova                             1
Noah Baumbach                               1
Eva Küpper                                  1
Albert Dupontel                             1
Robert Machoian                             1
Saeed Roustaee                              1
Paula van der Oest                          1
Leonardo Guerra Seràgnoli                   1
Jim Jarmusch                                1
 Spike Jonze                                1
Philippe Lacôte                             1
Yorgos Lanthimos                            1
Herman van der Horst                        1
Rodrigo Bellott                             1
Wanuri Kahiu                                1
Dominik Moll                                1
Delphine Lehericey                          1
Fabian Jansen                               1
Praveen Morchhale                           1
Marc Munden                                 1
Agnieszka Holland                           1
Adewale Akinnuoye-Agbaje                    1
Shatara Michelle Ford                       1
Ric Burns                                   1
Kentucker Audley, Albert Birney             1
Jean-François Laguionie, Xavier Picard      1
Daniel Graham                               1
Fernanda Valadez                            1
Tadhg O'Sullivan                            1
Jörg Adolph                                 1
Ike Bertels                                 1
Elizabeth Lo                                1
Hou Hsiao-hsien                             1
Desiree Akhavan                             1
Pedro Almodóvar                             1
Guido Hendrikx                              1
Anne-Lise Koehler, Éric Serre               1
Annemarie van de Mond                       1
Mark Verkerk                                1
Rémi Chayé                                  1
Sébastien Lifshitz                          1
Aurel                                       1
Philippe Godeau                             1
Kaweh Modiri                                1
Julie Dash                                  1
Johanne Helgeland                           1
Sean Durkin                                 1
Ben van Lieshout                            1
Sabine Lubbe Bakker, Niels van Koevorden    1
James Erskine                               1
Benh Zeitlin                                1
Heddy Honigmann                             1
Kitty Green                                 1
Noah Hutton                                 1
 Jim Jarmusch                               1
Maxime Govare, Cédric le Gallo              1
Ferzan Özpetek                              1
Bert Stern                                  1
Frank Scheffer                              1
Claude Lelouch                              1
Ana Katz                                    1
Demaizière, Alban Teurlai                   1
Name: regisseur, dtype: int64

In [9]:
name='Wong Kar Wai'
mv[mv.regisseur == name][['title']]

                   title
9   In the Mood for Love
10                  2046
11     Chungking Express
12         Fallen Angels
13        Happy Together
14              The Hand

In [10]:
imdb_rat_mv['title_norm'] = imdb_rat_mv.title.str.casefold()
imdb_rat_mv['director_norm'] = imdb_rat_mv.director.str.casefold()

In [12]:
# unfortunetaly only a few movies can be foind in IMDB database
res = pd.merge(mv,imdb_rat_mv, on='title_norm', how='inner')
res.head()

,title_x,description_x,pa,te_zien_tot,genre_x,land,taal,ondertitels,speelduur,regisseur,distributeur,min_age,duration_min,director_norm_x,title_norm,primary_genre,weighted_average_vote,total_votes,mean_vote,median_vote,votes_10,votes_9,votes_8,votes_7,votes_6,votes_5,votes_4,votes_3,votes_2,votes_1,allgenders_0age_avg_vote,allgenders_0age_votes,allgenders_18age_avg_vote,allgenders_18age_votes,allgenders_30age_avg_vote,allgenders_30age_votes,allgenders_45age_avg_vote,allgenders_45age_votes,males_allages_avg_vote,males_allages_votes,males_0age_avg_vote,males_0age_votes,males_18age_avg_vote,males_18age_votes,males_30age_avg_vote,males_30age_votes,males_45age_avg_vote,males_45age_votes,females_allages_avg_vote,females_allages_votes,females_0age_avg_vote,females_0age_votes,females_18age_avg_vote,females_18age_votes,females_30age_avg_vote,females_30age_votes,females_45age_avg_vote,females_45age_votes,top1000_voters_rating,top1000_voters_votes,us_voters_rating,us_voters_votes,non_us_voters_rating,non_us_voters_votes,title_y,original_title,year,date_published,genre_y,duration,country,language,director,writer,production_company,actors,description_y,avg_vote,votes,budget,usa_gross_income,worlwide_gross_income,metascore,reviews_from_users,reviews_from_critics,director_norm_y
0,La dea fortuna,Alessandro en Arturo staan op het punt na 15 j...,Mogelijk schadelijk tot 9 jaar,6 december 2021,drama,Italië,Italiaans,Nederlands,114 min.,Ferzan Özpetek,Arti Film,9,114,ferzan özpetek,la dea fortuna,drama,6.0,1112,6.2,7.0,59,65,186,321,218,70,36,23,28,106,3.3,8.0,5.5,212.0,5.7,296.0,5.8,204.0,6.0,531.0,2.4,5.0,6.1,120.0,5.9,194.0,6.0,159.0,4.7,190.0,4.7,3.0,4.2,69.0,5.0,71.0,4.2,32.0,5.7,31.0,2.2,100.0,6.3,475.0,La dea fortuna,La dea fortuna,2019,2019-12-19,Drama,114,Italy,Italian,Ferzan Ozpetek,"Ferzan Ozpetek, Silvia Ranfagni",R&C Produzioni,"Stefano Accorsi, Jasmine Trinca, Edoardo Leo, ...","When Annamaria, a longtime friend of Alessandr...",6.0,1112,EUR 4000000,NaN,$ 9780218,NaN,NaN,7.0,ferzan ozpetek
1,In the Mood for Love,Tony Leung en Maggie Cheung ontmoeten elkaar i...,Alle leeftijden,6 december 2021,"drama, romantiek",Hongkong,Kantonees,Nederlands,98 min.,Wong Kar Wai,Cinéart Nederland,0,98,wong kar wai,in the mood for love,drama,8.1,119171,8.1,8.0,26474,25993,32294,18443,7361,3243,1640,977,744,2002,8.4,65.0,8.2,22947.0,8.0,50790.0,7.9,13731.0,8.0,69859.0,8.4,41.0,8.1,16595.0,8.0,39144.0,7.9,11040.0,8.2,20510.0,8.9,20.0,8.2,5964.0,8.2,10963.0,8.1,2459.0,7.0,484.0,8.1,15724.0,8.0,60256.0,In the Mood for Love,Fa yeung nin wah,2000,2000-10-27,"Drama, Romance",98,"Hong Kong, China","Cantonese, Shanghainese, French, Spanish",Kar-Wai Wong,Kar-Wai Wong,Block 2 Pictures,"Maggie Cheung, Tony Chiu-Wai Leung, Ping Lam S...","Two neighbors, a woman and a man, form a stron...",8.1,119171,NaN,$ 2738980,$ 12854953,85.0,422.0,149.0,kar-wai wong
2,2046,Na het succes van In the Mood for Love (2000) ...,Mogelijk schadelijk tot 12 jaar,6 december 2021,"drama, romantiek, sciencefiction",Hong Kong,"Kantonees, Japans, Mandarijn",Nederlands,129 min.,Wong Kar Wai,Cinéart Nederland,12,129,wong kar wai,2046,drama,7.4,49774,7.5,8.0,6829,7885,13329,11037,5225,2378,1190,688,489,724,6.2,21.0,7.7,5646.0,7.4,26996.0,7.2,7478.0,7.4,32039.0,6.0,15.0,7.7,3877.0,7.4,21103.0,7.1,6251.0,7.6,8634.0,6.7,6.0,7.7,1678.0,7.6,5544.0,7.5,1118.0,6.5,379.0,7.4,7694.0,7.4,28670.0,2046,2046,2004,2004-10-29,"Drama, Romance, Sci-Fi",129,"Hong Kong, China, France, Italy, Germany","Cantonese, Japanese, Mandarin",Kar-Wai Wong,Kar-Wai Wong,Jet Tone Production,"Tony Chiu-Wai Leung, Li Gong, Faye Wong, Takuy...",Several women enter a science fiction author's...,7.4,49774,$ 12000000,$ 1444588,$ 19470239,78.0,226.0,196.0,kar-wai wong
3,Fallen Angels,Ook het vervolg op Chungking Express is een st...,Mogelijk schadelijk tot 16 jaar,6 december 2021,"crime, drama, komedie",Hongkong,Kantonees,Nederlands,99 min.,Wong Kar Wai,Cinéart Nederland,16,99,wong kar wai,fallen angels,crime,3.4,428,5.1,4.0,77,8,24,63,20,18,48,42,54,74,NaN,NaN,2.6,15.0,3.4,175.0,3.2,180.0,3.2,290.0,NaN,NaN,2.6,7.0,3.5,125.0,3.1,155.0,3.4,81.0,NaN,NaN,2.8,8.0,2.6,48.0,4.5,24.0,3.2,20.0,3.4,255.0,3.4,100.0,Fallen Angels,Fallen Angels,2006,2007-10-05,"Horror, Thriller",97,USA,English,Jeff Thomas,Jeff Thomas,Fallen Angels Productions,"Michael Dorn, Bill Moseley, Adrianne Curry, Mi...",When a turn of the century prison reformatory ...,3.4,428,NaN,NaN,NaN,NaN,8.0,12.0,jeff thomas
4,Happy Together,Hongkong-supersterren Tony Leung en Leslie Che...,Mogelijk schadelijk tot 12 jaar,6 december 2021,"drama, romantiek",Hong Kong,"Mandarijn, Spaans, Kantonees",Nederlands,96 min.,Wong Kar Wai,Cinéart Nederland,12,96,wong kar wai,happy together,drama,7.8,21543,7.9,8.0,3663,3980,6423,4210,1705,682,318,168,127,267,7.7,16.0,8.0,4011.0,7.7,9204.0,7.3,2977.0,7.7,12483.0,7.9,12.0,7.9,2583.0,7.7,7035.0,7.3,2428.0,7.9,4085.0,7.5,4.0,8.1,1330.0,7.9,2027.0,7.6,505.0,6.3,255.0,7.7,3174.0,7.7,11264.0,Happy Together,Chun gwong cha sit,1997,1997-09-26,"Drama, Romance",96,"Hong Kong, Japan, South Korea","Mandarin, Cantonese, Spanish",Kar-Wai Wong,"Manuel Puig, Kar-Wai Wong",Block 2 Pictures,"Leslie Cheung, Tony Chiu-Wai Leung, Chen Chang...",A couple take a trip to Argentina but both men...,7.8,21543,$ 4200000,$ 320319,$ 320319,69.0,87.0,45.0,kar-wai wong

In [27]:
# let's get votes per director
name='Kar-Wai Wong'
imdb_rat_mv_dir = imdb_rat_mv.dropna(axis=0,subset=['director'])[imdb_rat_mv_dir.director.str.contains(name)].copy()
imdb_rat_mv_dir[['title','director','weighted_average_vote']]

                              title      director  weighted_average_vote
imdb_title_id
tt0096461            As Tears Go By  Kar-Wai Wong                    7.0
tt0101258        Days of Being Wild  Kar-Wai Wong                    7.6
tt0109424         Hong Kong Express  Kar-Wai Wong                    8.1
tt0109688             Ashes of Time  Kar-Wai Wong                    7.2
tt0112913            Angeli perduti  Kar-Wai Wong                    7.7
tt0118694      In the Mood for Love  Kar-Wai Wong                    8.1
tt0118845            Happy Together  Kar-Wai Wong                    7.8
tt0212712                      2046  Kar-Wai Wong                    7.4
tt0765120        Un bacio romantico  Kar-Wai Wong                    6.6
tt1462900           The Grandmaster  Kar-Wai Wong                    6.6

In [28]:
imdb_rat.columns

Index(['weighted_average_vote', 'total_votes', 'mean_vote', 'median_vote',
       'votes_10', 'votes_9', 'votes_8', 'votes_7', 'votes_6', 'votes_5',
       'votes_4', 'votes_3', 'votes_2', 'votes_1', 'allgenders_0age_avg_vote',
       'allgenders_0age_votes', 'allgenders_18age_avg_vote',
       'allgenders_18age_votes', 'allgenders_30age_avg_vote',
       'allgenders_30age_votes', 'allgenders_45age_avg_vote',
       'allgenders_45age_votes', 'males_allages_avg_vote',
       'males_allages_votes', 'males_0age_avg_vote', 'males_0age_votes',
       'males_18age_avg_vote', 'males_18age_votes', 'males_30age_avg_vote',
       'males_30age_votes', 'males_45age_avg_vote', 'males_45age_votes',
       'females_allages_avg_vote', 'females_allages_votes',
       'females_0age_avg_vote', 'females_0age_votes', 'females_18age_avg_vote',
       'females_18age_votes', 'females_30age_avg_vote', 'females_30age_votes',
       'females_45age_avg_vote', 'females_45age_votes',
       'top1000_voters_rating', 'top1000_voters_votes', 'us_voters_rating',
       'us_voters_votes', 'non_us_voters_rating', 'non_us_voters_votes'],
      dtype='object')

## IMDB's weigted rating formula:
WeightedRating(WR)= (v/(v+m)*R)+(m/(v+m)*C)

where
- v is the number of votes for the movie;
- m is the minimum votes required to be listed in the chart;
- R is the average rating of the movie;
- C is the mean vote across the whole report.

In [29]:
m_perc = .8 # hyperparam
C = imdb_rat.mean_vote.mean()
m = imdb_rat.total_votes.quantile(m_perc)
print(C)
print(m)

6.226342088404868
2722.0

In [30]:
def imdb_wr(r):
    v = r.total_votes
    R = r.mean_vote
    return (v/(v+m)*R)+(m/(v+m)*C)

In [33]:
# Let's calculate IMDB weighted ratings for our movies of the selected director
imdb_rat_mv_dir['imdb_wr'] = imdb_rat_mv_dir.apply(imdb_wr, axis=1)

In [34]:
imdb_rat_mv_dir[['director','title','imdb_wr']]

                   director                 title   imdb_wr
imdb_title_id
tt0096461      Kar-Wai Wong        As Tears Go By  6.878328
tt0101258      Kar-Wai Wong    Days of Being Wild  7.501244
tt0109424      Kar-Wai Wong     Hong Kong Express  8.018720
tt0109688      Kar-Wai Wong         Ashes of Time  7.112816
tt0112913      Kar-Wai Wong        Angeli perduti  7.643845
tt0118694      Kar-Wai Wong  In the Mood for Love  8.058159
tt0118845      Kar-Wai Wong        Happy Together  7.712252
tt0212712      Kar-Wai Wong                  2046  7.433959
tt0765120      Kar-Wai Wong    Un bacio romantico  6.771055
tt1462900      Kar-Wai Wong       The Grandmaster  6.661556